package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String username) {
        Test testuser = new Test(username);
        userRepository.save(testuser);
        return "done";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Test> getAllUsers() {
        // This returns a JSON or XML with the users
//        System.out.println("testing what is coming out the postgres");
//        userRepository
//                .findAll();
//
//        for (Test test : userRepository.findAll())
//            System.out.println(test.getUsername());

        return userRepository.findAll();
    }
}